---
domain: demo

consul_version: "1.7.2"
nomad_version: "0.11.0-beta1"
coredns_version: "1.6.9"
traefik_version: "2.2.0"

random_hash: "{{ lookup('password', '/tmp/randomhash chars=ascii_letters,digits,hexdigits length=32') }}"
interface: enp0s8
