---
- hosts: consul_nomad
  become: yes
  roles:
    - name: base
    - name: jre
    - name: docker
    - name: consul
    - name: nomad

- hosts: loadbalancer
  become: yes
  roles:
    - name: coredns
    - name: traefik
    - name: prometheus

  post_tasks:
