---
- hosts: consul_nomad
  become: yes
  roles:
    - name: jre
    - name: docker
      tags: ['docker']
    - name: vault
      tags: ['vault']
    - name: nomad
      tags: ['nomad']

  post_tasks:
    - name: Disable systemd-resolved service
      systemd:
        name: systemd-resolved
        state: stopped
        enabled: no
      tags: ['always']

    - name: Set nameserver to localhost
      copy:
        content: "nameserver {{ loadbalancer_ip }}"
        dest: /etc/resolv.conf
      tags: ['always']

    - name: Restart Docker to pick up DNS change
      systemd:
        name: docker
        state: restarted
      tags: ['docker']


- hosts: loadbalancer
  become: yes
  roles:
    - name: coredns
    - name: traefik


- hosts: localhost
  tasks:
    - name: Run all jobs on Nomad # noqa 301
      command: vagrant ssh consul-nomad-node1 -c 'for job in nomad_jobs/*.nomad; do nomad job run "$job"; done'
