---
- hosts: consul_nomad
  become: yes
  roles:
    - name: consul-nomad-dependencies
    - name: consul
    - name: nomad

- hosts: loadbalancer
  become: yes
  roles:
    - name: coredns
    - name: traefik
    - name: prometheus

  post_tasks:
