---
- hosts: consul_nomad
  become: yes
  roles:
    - name: base
    - name: jre
    - name: docker
    - name: consul
    - name: nomad

  post_tasks:
    - name: Disable systemd-resolved service
      systemd:
        name: systemd-resolved
        state: stopped
        enabled: no

    - name: Set nameserver to localhost
      copy:
        content: "nameserver {{ loadbalancer_ip }}"
        dest: /etc/resolv.conf


- hosts: loadbalancer
  become: yes
  roles:
    - name: coredns
    - name: traefik
    - name: prometheus

  post_tasks:
