---
- hosts: consul_nomad
  become: yes
  roles:
    - name: consul-nomad-dependencies
    - name: consul
    - name: nomad

- hosts: loadbalancer
  become: yes
  roles:
    - name: coredns
    - name: traefik
    - name: prometheus

- hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - name: jar-server-dockerimage

  post_tasks:
    - name: Run 'jar-server' job on Nomad # noqa 301
      command: vagrant ssh consul-nomad-node1 -c 'nomad job run ~/jar-server.nomad'
