---
- name: Check if Docker is installed
  delegate_to: localhost
  command: docker version
  register: _docker_result
  failed_when: false
  changed_when: false

- name: Build and push Docker image
  block:
    - name: Install Python 3
      package:
        name: "python3"
        state: present

    - name: Check if pip is installed along Python 3 # noqa 301
      shell: command -v pip3 >/dev/null 2>&1
      register: _pip_exist
      ignore_errors: yes

    - name: Install pip3
      package:
        name: "{{ item }}"
        state: present
      loop:
        - python3-pip
        - python3-setuptools
      when: not _pip_exist

    - name: Install Python Docker library
      pip: name=docker

    - name: Log into DockerHub
      docker_login:
        username: "{{ lookup('env','ANSIBLE_DOCKER_USERNAME') }}"
        password: "{{ lookup('env','ANSIBLE_DOCKER_PASSWORD') }}"

    - name: Build local Docker image
      docker_image:
        build:
          path: "{{ playbook_dir }}/roles/jar-server/files"
          pull: yes
        name: jar-server-demo
        repository: "docker.io/{{ lookup('env','ANSIBLE_DOCKER_USERNAME') }}/jar-server-demo"
        push: yes
        source: build
  when:
    - _docker_result.rc == 0
    - lookup('env','ANSIBLE_DOCKER_USERNAME') is defined
    - lookup('env','ANSIBLE_DOCKER_PASSWORD') is defined
