---
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "consul"
    consul_sd_configs:
      - server: "consul:8500"
        tags: ["prometheus"]
    relabel_configs:
      - source_labels: [__meta_sd_consul_tags]
        separator: ','
        regex: label:([^=]+)=([^,]+)
        target_label: ${1}
        replacement: ${2}
      - target_label: instance
        replacement: "consul"

  - job_name: "consul_exporter"
    static_configs:
      - targets: ["localhost:9107"]
    relabel_configs:
      - target_label: instance
        replacement: "consul"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    relabel_configs:
      - target_label: instance
        replacement: "loadbalancer"

  - job_name: "traefik"
    static_configs:
      - targets: ["localhost:8080"]
    relabel_configs:
      - target_label: instance
        replacement: "loadbalancer"
