---
- name: Install Python 3
  delegate_to: localhost
  package:
    name: "python3"
    state: present

- name: Check if pip is installed along Python 3 # noqa 301
  shell: command -v pip3 >/dev/null 2>&1
  register: _pip_exist
  ignore_errors: yes

- name: Install pip3
  delegate_to: localhost
  package:
    name: "{{ item }}"
    state: present
  loop:
    - python3-pip
    - python3-setuptools
  when: not _pip_exist

- name: Install Python Docker library
  delegate_to: localhost
  pip: name=docker

- name: Log into DockerHub
  delegate_to: localhost
  docker_login:
    username: "{{ lookup('env','ANSIBLE_DOCKER_USERNAME') }}"
    password: "{{ lookup('env','ANSIBLE_DOCKER_PASSWORD') }}"

- name: Build local Docker image
  delegate_to: localhost
  docker_image:
    build:
      path: "{{ playbook_dir }}/roles/jar-server/files"
      pull: yes
    name: jar-server-demo
    repository: "docker.io/{{ lookup('env','ANSIBLE_DOCKER_USERNAME') }}/jar-server-demo"
    push: yes
    source: build
