---
- name: Check if Docker is installed on localhost
  delegate_to: localhost
  command: docker version
  register: _docker_result
  failed_when: false
  changed_when: false

- name: Build and push Docker image (localhost)
  include_tasks: localhost.yml
  when:
    - _docker_result.rc == 0
    - lookup('env','ANSIBLE_DOCKER_USERNAME') is defined
    - lookup('env','ANSIBLE_DOCKER_PASSWORD') is defined

- name: Copy 'jar-server' job config
  become: true
  template:
    src: "jar-server.nomad.j2"
    dest: "{{ ansible_env.HOME }}/jar-server.nomad"
    mode: 0644

- name: Run 'jar-server' job on Nomad # noqa 301
  become: true
  command: nomad job run "{{ ansible_env.HOME }}/jar-server.nomad"
