---
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/ansible-lint
